### ISSUE TITLE
Rings tool: Center Point parameter does not handle coordinates entered in Long Lat order (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#222]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21410669/5d8f5404-c797-11e6-8bd9-f9d51cfa4f4c.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21410671/6127cbaa-c797-11e6-9274-e86437af05c4.png)

**Comment by rjones0** [comment]
I have a fix for this locally, will make pull request when possible.

**Comment by kgonzago** [comment]
Issues #218, #220, and this current issue are all related. The logic I'm working on will fix all three issues simultaneously.

**Comment by kgonzago** [comment]
Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/498)

**Comment by ACueva** [comment]
Checklist test updated and verified. https://github.com/ArcGIS/solutions-defense-test-catalog/commit/bc6846542b5a0e6aa99cf11e2dc6f03b26b29f24

**Comment by ACueva** [comment]
This issue still needs the appropriate labels applied for the issue addressed search functionality.

**Comment by ACueva** [comment]
Closing issue temporarily to make sure it gets listed in the "issues addressed" section.

**Comment by ACueva** [comment]
Confirmed this issue appears in the "issues addressed" section.
![2018-02-27_12-33-37](https://user-images.githubusercontent.com/3093940/36753247-77a61986-1bba-11e8-82eb-800c5993bee7.png)
