### ISSUE TITLE
Geodesy lines (Lines and Radials) don't split for Geographic Coordinate Systems

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#226]
In fixing #180 there is a new challenge to working with geodesy lines in geographic coordinate systems in ArcGIS Pro. Basically lines that cross the dateline should "split" and move to the other side of the map. This works for Projected Coordinate Systems, but isn't working for Geographic Coordinate Systems (of the Map). This problem is illustrated in the notes from the previous issue that are copied here:

----------------------------------------------

So here is our Lines (Geodesic) and Range Ring (with Radials) in Pro with a Mercator projection (no, not Web Mercator). What I am expecting to see is Lines that bend (Geodesic) and Radials that are straight (they define a bearing and are therefore loxodromes). Loxodromes are straight in a Mercator projection.
![image](https://cloud.githubusercontent.com/assets/3093182/21435461/e48c0122-c82e-11e6-8b0f-d8114efe1b73.png)

WOOHOO!

Now if we use WGS 1984....
![image](https://cloud.githubusercontent.com/assets/3093182/21435830/ac636e5a-c830-11e6-8d37-6111be198579.png)
We get some weirdness going across the dateline.

In another projected ... Robinson (think National Geographic's world maps):
![image](https://cloud.githubusercontent.com/assets/3093182/21435741/410e52aa-c830-11e6-8415-294c6f998312.png)

Back to another GCS, this time GRS 1980:
![image](https://cloud.githubusercontent.com/assets/3093182/21435984/4027c6f4-c831-11e6-9053-9b807b11fe69.png)

**Comment by topowright** [comment]
This issue can be closed based on our updates to the dialog prompt that happens when you try to draw a line out of bounds of the map: 
![image](https://user-images.githubusercontent.com/5488313/36299303-34276dde-12b1-11e8-81b9-e26741dc3c1e.png)

**Comment by ACueva** [comment]
Added to "Issues Addressed" section in Distance and Direction Release notes. Assigning to @dfoll for review.

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by ACueva** [comment]
Removing this issue from the "Issues addressed" section as there is no issue.  Issue has been marked with "non-reproducible"already.

**Comment by topowright** [comment]
I think this still needs to be in the issues addressed being that it was apart of older docucmenation: 
http://solutions.arcgis.com/defense/help/distance-direction/arcgis-pro/known-issues-for-distance-and-direction-in-arcgis-pro.htm

**Comment by lfunkhouser** [comment]
@topowright @ACueva Please be clear and update the comments with more specific information regarding the version it was addressed in or the version that was non-reproducible. Issue appears to have been reported in the Pro 1.4 add-in and added to the known issues for the first 3 releases of DD and MT. This issue appears to have been addressed between 1.4 and 2.1.

**Comment by BobBooth** [comment]
This is still reproducible.  In Pro 2.1.0 with the 4/17/18 build of Military Tools.
If you set up the Pro map with GCS WGS84 and check the "Enable wrapping around the date line" box:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/3ad73103-0119-44bf-ac7f-8322a0bb900d)
Then you can draw geodesic features across the Date Line in pro with Distance and Direction tools, and they wrap nicely.
Circles and Ellipses get a split line down the Date Line, but they all draw fine.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/ac94e929-1d0b-4981-9f71-3fe26726d215)
However, if you don't have that box checked, then the geodetic lines and the radials of the range rings that cross the Date Line will hang off into white space.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/f360b739-2bf8-4403-a653-adf7fbad1ff6)

**Comment by BobBooth** [comment]
@csmoore  - if we move to features for Pro (to support labeling), this issue will probably be obsolete, correct?

**Comment by lfunkhouser** [comment]
Please retest to see if this is invalid now that lines will be drawn as features rather than graphics
@ACueva @topowright @dfoll

**Comment by topowright** [comment]
Since we have moved to features this issue is now non reproducible. Closing 
![image](https://user-images.githubusercontent.com/5488313/44863749-cea40c80-ac32-11e8-8ad0-84dd555bf484.png)
