### ISSUE TITLE
Distance and Direction - Pane Title - ArcGIS Pro

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#240]
On the ribbon it has a lowercase "a", but in the pane it as an uppercase "A".

It should be Distance and Direction in both places, not Distance And Direction.

![image](https://cloud.githubusercontent.com/assets/5016557/21700530/c2202974-d355-11e6-84c1-38dbae79c3f0.png)

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to verify fix.

**Comment by topowright** [comment]
This is still an issue:

**Comment by topowright** [comment]
![image](https://cloud.githubusercontent.com/assets/5488313/25642924/b27be172-2f51-11e7-85f5-6821f9c79a1a.png)
I see that there was change in the code; however, the dock pane is still showing up wrong.

**Comment by pHill5136** [comment]
looks like this has been fixed. Please verify

**Comment by dfoll** [comment]
still seeing this in 1474 
![image](https://cloud.githubusercontent.com/assets/5322669/26122715/433c72cc-3a2d-11e7-8420-504037f52ac8.png)
the ArcMap add-in uses a small "a" for "and" suggest we go with that

**Comment by pHill5136** [comment]
@dfoll This should be fixed now. Had to modify the combined addin

**Comment by dfoll** [comment]
sending this one back over, 1484  still looks like this

**Comment by dfoll** [comment]
looks good in 1487 for combined and single add-in
