### ISSUE TITLE
units naming inconsistent for miles on rings tab

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#432]
When using DD on the rings tab.  The name for the distance units will vary depending on how the rings were created.  In interactive mode the name for miles is **Mile_USs**  vs entering input values the name for miles is **Miles**.  See screen grab below. 

Interactive mode:
![image](https://user-images.githubusercontent.com/5116835/27649543-f0266d96-5be6-11e7-8b26-0d2d6da89252.png)

Input mode:
![image](https://user-images.githubusercontent.com/5116835/27649481-c287a738-5be6-11e7-80d5-ed5a3e01a7b6.png)

**Comment by NatalieCampos** [comment]
@pHill5136 unable to verify this on build 1622

**Comment by NatalieCampos** [comment]
Slightly better but still a typo on build 1622.  See graphic.  @nfeuerstein I dont think this is a show stopper can this be moved to version after next?

![image](https://user-images.githubusercontent.com/5116835/27655274-a9b31f54-5bf9-11e7-86df-fe63f442bf54.png)

**Comment by pHill5136** [comment]
fixed typo pleas verify

**Comment by NatalieCampos** [comment]
@pHill5136 as of build 1624 (the 1pm build) this is still an issue.  See the screen grab below.  

![image](https://user-images.githubusercontent.com/5116835/27659913-fec6f456-5c09-11e7-84c7-a2cbd2c4f688.png)

**Comment by NatalieCampos** [comment]
@pHill5136 this has been fixed in build 1625.

![image](https://user-images.githubusercontent.com/5116835/27661674-0c9fcf84-5c10-11e7-94c8-ce613fb6d594.png)
